name: Diff screenshots via Pull Request

on:
  workflow_call:
    inputs:
      node_version:
        description: e.g. x.y.z
        required: true
        type: string
      install_command:
        description: e.g. npm ci
        required: true
        type: string
      snapshots_command:
        description: e.g. npm run snapshot
        required: true
        type: string
      snapshots_dirpath:
        description: e.g. test/vrt.e2e.ts-snapshots
        required: true
        type: string
      your_repo:
        description: e.g. github.repository
        type: string
        default: ${{ github.repository }}
      vrt_repo:
        description: e.g. org_name/vrt-workflows-2024
        required: true
        type: string
      playwright_image_tag:
        description: e.g. v1.49.1-noble
        type: string
        default: latest
      force_update_base_snapshots:
        description: e.g. true or false
        type: boolean
        default: false
      cache_key:
        description: pass to key of actions/cache@v4
        type: string
      cache_paths:
        description: pass to pathes of actions/cache@v4
        type: string
      cache_restore_keys:
        description: pass to restore-keys of actions/cache@v4
        type: string
      shard_count:
        description: append argument --shard=1/n to the snapshots_command
        type: number
        default: 4
    secrets:
      your_repo_github_token:
        required: true
      vrt_repo_github_token:
        required: true
      env_gpr_read_token:
        required: false

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      shard_indexes_json: ${{ steps.vars.outputs.shard_indexes_json }}
      vrt_diff_temp_branch: ${{ steps.vars.outputs.vrt_diff_temp_branch }}
      vrt_diff_dirname: ${{ steps.vars.outputs.vrt_diff_dirname }}
      vrt_diff_workspace: ${{ steps.vars.outputs.vrt_diff_workspace }}
      vrt_diff_base_branch: ${{ steps.vars.outputs.vrt_diff_base_branch }}
      base_sha: ${{ steps.vars.outputs.base_sha }}
      head_sha: ${{ steps.vars.outputs.head_sha }}
      required_base_snapshots: ${{ steps.checkouts.outputs.required_base_snapshots }}
    steps:
      - name: Setup variables
        run: |
          echo "shard_indexes_json=$(seq ${{ inputs.shard_count }} | jq -cs 'map("\(.)")')" > $GITHUB_OUTPUT
          echo "vrt_diff_temp_branch=diff" >> $GITHUB_OUTPUT
          echo "vrt_diff_dirname=diff" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "vrt_diff_workspace=.vrt-diff-${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
            echo "vrt_diff_base_branch=snapshots/${{ inputs.your_repo }}/${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "base_sha=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "head_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "vrt_diff_workspace=.vrt-diff-${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "vrt_diff_base_branch=snapshots/${{ inputs.your_repo }}/${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "base_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
        id: vars
      - name: Clone vrt repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.vrt_repo }}
          ref: ${{ steps.vars.outputs.vrt_diff_base_branch }}
          path: ${{ steps.vars.outputs.vrt_diff_workspace }}
          token: ${{ secrets.vrt_repo_github_token }}
        continue-on-error: true
        id: base
      - name: Set required base snapshots on failure
        run: echo "required_base_snapshots=true" >> $GITHUB_OUTPUT
        if: steps.base.outcome == 'failure' || inputs.force_update_base_snapshots
        id: checkouts

  base:
    if: needs.init.outputs.required_base_snapshots
    needs: init
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:${{ inputs.playwright_image_tag }}
    env:
      GPR_READ_TOKEN: ${{ secrets.env_gpr_read_token }}
    strategy:
      matrix:
        shard_index: ${{ fromJson(needs.init.outputs.shard_indexes_json) }}
        shard_total:
          - ${{ inputs.shard_count }}
    steps:
      - name: Set safe directory for permission on docker container
        run: git config --global --add safe.directory "$(pwd)"
      - name: Clone your repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.your_repo }}
          token: ${{ secrets.your_repo_github_token }}
          ref: ${{ needs.init.outputs.base_sha }}
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Restore some caches
        uses: actions/cache@v4
        with:
          key: ${{ inputs.cache_key }}
          path: ${{ inputs.cache_paths }}
          restore-keys: ${{ inputs.cache_restore_keys }}
        if: inputs.cache_key
      - name: Install npm modules on base
        run: ${{ inputs.install_command }}
      - name: Take snapshots on base
        run: ${{ inputs.snapshots_command }} --shard ${{ matrix.shard_index }}/${{ matrix.shard_total }}
      - name: Upload base snapshots
        uses: actions/upload-artifact@v4
        with:
          name: base_snapshots_${{ matrix.shard_index }}
          path: ${{ inputs.snapshots_dirpath }}
          retention-days: 3
      - name: Upload test-results on failure for debug
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 3
        if: failure()

  commit_base:
    needs: [init, base]
    runs-on: ubuntu-latest
    steps:
      - name: Clone vrt repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.vrt_repo }}
          path: ${{ needs.init.outputs.vrt_diff_workspace }}
          token: ${{ secrets.vrt_repo_github_token }}
      - name: Download base snapshots
        uses: actions/download-artifact@v4
        with:
          path: ${{ needs.init.outputs.vrt_diff_workspace }}/${{ needs.init.outputs.vrt_diff_dirname }}
          pattern: base_snapshots_*
          merge-multiple: true
      - name: Push vrt by base branch
        run: |
          cd ${{ needs.init.outputs.vrt_diff_workspace }}
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git checkout -b ${{ needs.init.outputs.vrt_diff_base_branch }}
          git add ${{ needs.init.outputs.vrt_diff_dirname }}
          git commit -m "Update screenshots [ci skip]"
          git push origin HEAD:${{ needs.init.outputs.vrt_diff_base_branch }} -f

  head:
    if: ${{ github.event_name == 'pull_request' && !cancelled() && !failure() }}
    needs: [init, commit_base]
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:${{ inputs.playwright_image_tag }}
    env:
      GPR_READ_TOKEN: ${{ secrets.env_gpr_read_token }}
    strategy:
      matrix:
        shard_index: ${{ fromJson(needs.init.outputs.shard_indexes_json) }}
        shard_total:
          - ${{ inputs.shard_count }}
    steps:
      - name: Set safe directory for permission on docker container
        run: git config --global --add safe.directory "$(pwd)"
      - name: Clone your repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.your_repo }}
          token: ${{ secrets.your_repo_github_token }}
          ref: ${{ needs.init.outputs.head_sha }}
      - name: Clone vrt repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.vrt_repo }}
          ref: ${{ needs.init.outputs.vrt_diff_base_branch }}
          path: ${{ needs.init.outputs.vrt_diff_workspace }}
          token: ${{ secrets.vrt_repo_github_token }}
      - name: Copy base snapshots from vrt
        run: cp -r ${{ needs.init.outputs.vrt_diff_workspace }}/${{ needs.init.outputs.vrt_diff_dirname }} ${{ inputs.snapshots_dirpath }}
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
      - name: Restore some caches
        uses: actions/cache@v4
        with:
          key: ${{ inputs.cache_key }}
          path: ${{ inputs.cache_paths }}
          restore-keys: ${{ inputs.cache_restore_keys }}
        if: inputs.cache_key
      - name: Install npm modules on head
        run: ${{ inputs.install_command }}
      - name: Mark timestamp before head snapshot
        run: touch /tmp/.before_snapshot_timestamp
      - name: Take snapshots on head
        run: ${{ inputs.snapshots_command }} --shard ${{ matrix.shard_index }}/${{ matrix.shard_total }}
      - name: Keep only updated snapshots for this shard
        run: find ${{ inputs.snapshots_dirpath }} -type f ! -newer /tmp/.before_snapshot_timestamp -exec rm -f {} +
      - name: Upload updated snapshots
        uses: actions/upload-artifact@v4
        with:
          name: updated_snapshots_${{ matrix.shard_index }}
          path: ${{ inputs.snapshots_dirpath }}
          retention-days: 3
      - name: Upload test-results on failure for debug
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 3
        if: failure()

  commit_head:
    if: ${{ !cancelled() && !failure() }}
    needs: [init, commit_base, head]
    runs-on: ubuntu-latest
    steps:
      - name: Clone vrt repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.vrt_repo }}
          ref: ${{ needs.init.outputs.vrt_diff_base_branch }}
          path: ${{ needs.init.outputs.vrt_diff_workspace }}
          token: ${{ secrets.vrt_repo_github_token }}
      - name: Download base snapshots
        uses: actions/download-artifact@v4
        with:
          path: ${{ needs.init.outputs.vrt_diff_workspace }}/${{ needs.init.outputs.vrt_diff_dirname }}
          pattern: base_snapshots_*
          merge-multiple: true
      - name: Download updated snapshots
        uses: actions/download-artifact@v4
        with:
          path: ${{ needs.init.outputs.vrt_diff_workspace }}/${{ needs.init.outputs.vrt_diff_dirname }}
          pattern: updated_snapshots_*
          merge-multiple: true
      - name: Push snapshots of head
        run: |
          cd ${{ needs.init.outputs.vrt_diff_workspace }}
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          git add -N ${{ needs.init.outputs.vrt_diff_dirname }}
          if ! git diff --exit-code --quiet ${{ needs.init.outputs.vrt_diff_dirname }}
          then
            git add ${{ needs.init.outputs.vrt_diff_dirname }}
            echo "added_count=$(git diff HEAD --diff-filter=A --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
            echo "changed_count=$(git diff HEAD --diff-filter=M --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
            echo "deleted_count=$(git diff HEAD --diff-filter=D --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
            git commit -m "Update screenshots [ci skip]"
            git push origin HEAD:${{ needs.init.outputs.vrt_diff_temp_branch }} -f
            echo "changed_snapshots_url=https://github.com/${{ inputs.vrt_repo }}/commit/$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          fi
        id: results
      - name: Create or update comment
        uses: actions/github-script@v7
        with:
          script: |
            const subject = "Visual Regression Test Result";
            const changedSnapshotUrl = '${{ steps.results.outputs.changed_snapshots_url }}';
            const addedCount = '${{ steps.results.outputs.added_count }}';
            const changedCount = '${{ steps.results.outputs.changed_count }}';
            const deletedCount = '${{ steps.results.outputs.deleted_count }}';
            const result = !changedSnapshotUrl
              ? "✅ No change"
              : `❗ Updated: ${changedCount}, Added: ${addedCount}, Deleted: ${deletedCount}`;
            const commentBody = `### ${subject}\n\n${result}\n${changedSnapshotUrl}`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const previousComment = comments.find(
              (comment) =>
                comment.user.login === "github-actions[bot]" &&
                comment.body.includes(subject)
            );

            if (previousComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: previousComment.id,
                body: commentBody,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody,
              });
            }
        if: github.event_name == 'pull_request'
