name: Diff screenshots via Pull Request

on:
  workflow_call:
    inputs:
      snapshots_command:
        description: e.g. npm run snapshot
        required: true
        type: string
      snapshots_dirpath:
        description: e.g. test/vrt.e2e.ts-snapshots
        required: true
        type: string
      npm_install_command:
        description: e.g. npm ci
        type: string
        default: npm ci
      your_repo:
        description: e.g. github.repository
        type: string
        default: ${{ github.repository }}
      vrt_repo:
        description: e.g. org_name/vrt-workflows-2024
        required: true
        type: string
    secrets:
      your_repo_github_token:
        required: true
      vrt_repo_github_token:
        required: true

jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Clone your repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ inputs.your_repo }}
          token: ${{ secrets.your_repo_github_token }}
      - name: Setup variables
        run: |
          echo "node_version=$(cat .node-version)" >> $GITHUB_OUTPUT
          echo "vrt_diff_temp_branch=diff" >> $GITHUB_OUTPUT
          echo "vrt_diff_dirname=diff" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "vrt_diff_workspace=.vrt-diff-${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
            echo "vrt_diff_base_branch=snapshots/${{ inputs.your_repo }}/${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "base_sha=${{ github.event.pull_request.base.sha }}" >> $GITHUB_OUTPUT
            echo "head_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "vrt_diff_workspace=.vrt-diff-${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "vrt_diff_base_branch=snapshots/${{ inputs.your_repo }}/${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "base_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
        id: vars
      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.vars.outputs.node_version }}
      - name: Clone vrt repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ inputs.vrt_repo }}
          path: ${{ steps.vars.outputs.vrt_diff_workspace }}
          token: ${{ secrets.vrt_repo_github_token }}
      - name: Checkout vrt by base branch
        run: |
          cd ${{ steps.vars.outputs.vrt_diff_workspace }}
          git config user.name  "GitHub Action"
          git config user.email "action@github.com"
          if ! git checkout ${{ steps.vars.outputs.vrt_diff_base_branch }}
          then
            git checkout -b ${{ steps.vars.outputs.vrt_diff_base_branch }}
            echo "required_snapshots=true" >> $GITHUB_OUTPUT
          fi
        id: checkouts
      - name: Checkout base
        run: git checkout ${{ steps.vars.outputs.base_sha }}
        if: steps.checkouts.outputs.required_snapshots
      - name: Install npm modules on base
        run: ${{ inputs.npm_install_command}}
        if: steps.checkouts.outputs.required_snapshots
      - name: Take snapshots on base
        run: ${{ inputs.snapshots_command }}
        if: steps.checkouts.outputs.required_snapshots
      - name: Copy snapshots to vrt on base
        run: cp -r ${{ inputs.snapshots_dirpath }} ${{ steps.vars.outputs.vrt_diff_workspace }}/${{ steps.vars.outputs.vrt_diff_dirname }}
        if: steps.checkouts.outputs.required_snapshots
      - name: Push snapshots of base
        run: |
          cd ${{ steps.vars.outputs.vrt_diff_workspace }}
          git add ${{ steps.vars.outputs.vrt_diff_dirname }}
          git commit -m "Update screenshots [ci skip]"
          git push origin HEAD:${{ steps.vars.outputs.vrt_diff_base_branch }} -f
        if: steps.checkouts.outputs.required_snapshots
      - name: Checkout head
        run: git checkout ${{ steps.vars.outputs.head_sha }}
        if: github.event_name == 'pull_request'
      - name: Install npm modules on head
        run: ${{ inputs.npm_install_command}}
        if: github.event_name == 'pull_request'
      - name: Take snapshots on head
        run: ${{ inputs.snapshots_command }}
        if: github.event_name == 'pull_request'
      - name: Copy snapshots to vrt on head
        run: |
          rm -rf ${{ steps.vars.outputs.vrt_diff_workspace }}/${{ steps.vars.outputs.vrt_diff_dirname }}
          cp -r ${{ inputs.snapshots_dirpath}} ${{ steps.vars.outputs.vrt_diff_workspace }}/${{ steps.vars.outputs.vrt_diff_dirname }}
        if: github.event_name == 'pull_request'
      - name: Push snapshots of head
        run: |
          cd ${{ steps.vars.outputs.vrt_diff_workspace }}
          git add -N ${{ steps.vars.outputs.vrt_diff_dirname }}
          if ! git diff --exit-code --quiet ${{ steps.vars.outputs.vrt_diff_dirname }}
          then
            git add ${{ steps.vars.outputs.vrt_diff_dirname }}
            echo "added_count=$(git diff HEAD --diff-filter=A --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
            echo "changed_count=$(git diff HEAD --diff-filter=M --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
            echo "deleted_count=$(git diff HEAD --diff-filter=D --name-only | wc -l | xargs)" >> $GITHUB_OUTPUT
            git commit -m "Update screenshots [ci skip]"
            git push origin HEAD:${{ steps.vars.outputs.vrt_diff_temp_branch }} -f
            echo "changed_snapshots_url=https://github.com/${{ inputs.vrt_repo }}/commit/$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          fi
        id: results
        if: github.event_name == 'pull_request'
      - name: Create commit statuses
        uses: actions/github-script@v7
        with:
          script: |
            const isUpdated = !!'${{ steps.results.outputs.changed_snapshots_url }}';
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: '${{ steps.vars.outputs.head_sha }}',
              state: 'success',
              context: 'VRT Result',
              target_url: '${{ steps.results.outputs.changed_snapshots_url }}',
              description: !isUpdated ? '✅ No change' : '❗ Updated: ' +
                'M'.repeat(${{ steps.results.outputs.changed_count }}) +
                'A'.repeat(${{ steps.results.outputs.added_count }}) +
                'D'.repeat(${{ steps.results.outputs.deleted_count }}),
            });
        if: github.event_name == 'pull_request'
